FROM cosmosinhand/django_web:latest
ENV PYTHONUNBUFFERED=1

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" > /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
RUN apk add --update --no-cache git
WORKDIR /code
COPY requirements-dev.txt requirements-dev.txt

RUN python -m pip install --upgrade pip
RUN pip3 install --upgrade pip setuptools wheel

RUN apk update && apk add build-base libzmq musl-dev python3 python3-dev zeromq-dev
RUN pip3 install -r requirements-dev.txt
COPY . /code/